## 텐서
텐서(Tensor)는 파이토치의 기본 단위이며 GPU 연산을 가능하게 한다. 또한 Numpy의 배열과 유사하여 손쉽게 다룰 수 있다.

In [2]:
#라이브러리 불러오기
import torch #Pytorch를 사용하기 위한 기본 라이브러리
import numpy as np #Numpy를 사용하기 위한 기본 라이브러리

### 1. 텐서 만들기

In [3]:
# 빈 텐서 생성
x = torch.empty(5,4) #5x4 행렬 생성
print(x) #초기화되지 않은 행렬인 경우 해당 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타난다.

tensor([[ 2.8026e-45,  2.6625e-44,  1.6241e-42,  1.8450e+28],
        [-8.3139e+31,  3.0988e-41,  1.2612e-44,  1.8015e+25],
        [-8.3133e+31,  3.0988e-41,  3.3631e-44,  1.1259e+24],
        [ 3.9791e+05,  4.4666e-41,  1.4013e-45,  6.8589e+22],
        [ 4.8403e+30,  6.9474e+22,  2.8026e-45,  5.6052e-45]])


In [ ]:
torch.ones(3,3) # 3x3 일 행렬

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(2) #2행 영 벡터

tensor([0., 0.])

In [ ]:
torch.rand(5,6) #5x6 랜덤 행렬

tensor([[0.7022, 0.0640, 0.6158, 0.5403, 0.4086, 0.3613],
        [0.8236, 0.6959, 0.8971, 0.2502, 0.6502, 0.8267],
        [0.8041, 0.4913, 0.4770, 0.1153, 0.3116, 0.4814],
        [0.5805, 0.3767, 0.0429, 0.2986, 0.3879, 0.8525],
        [0.5500, 0.0697, 0.6397, 0.2372, 0.0148, 0.5063]])

### 리스트, 넘파이 배열을 텐서로 만들기

In [4]:
l = [13,4] #리스트 생성
r = np.array([4,56,7]) #넘파이 배열 생성

In [5]:
torch.tensor(l) #리스트를 텐서로 쉽게 변환할 수 있다.

tensor([13,  4])

In [6]:
torch.tensor(r) #넘파이 배열을 텐서로 쉽게 변환할 수 있다.

tensor([ 4, 56,  7])

### 텐서의 크기와 타입 확인하기

In [9]:
x.size()

torch.Size([5, 4])

In [10]:
x.shape

torch.Size([5, 4])

In [7]:
x.size()[1] #.size()는 텐서의 크기를 확인할 수 있으며 매우 자주 사용된다.

4

In [8]:
type(x) #type은 Python에서 사용되는 모든 것들의 종류를 보여준다.

torch.Tensor

### 텐서의 덧셈

In [11]:
x = torch.rand(2,2) #2x2 랜덤 행렬
y = torch.rand(2,2) #2x2 랜덤 행렬
print(x)
print(y)

tensor([[6.3023e-01, 1.0020e-04],
        [8.6599e-01, 9.6441e-01]])
tensor([[0.8839, 0.8771],
        [0.0025, 0.2814]])


In [12]:
x+y #두 텐서의 합

tensor([[1.5141, 0.8772],
        [0.8685, 1.2458]])

In [13]:
torch.add(x,y) #두 텐서의 합의 또 다른 표현

tensor([[1.5141, 0.8772],
        [0.8685, 1.2458]])

In [14]:
y.add(x) #두 텐서의 합의 또 다른 표현이지만 이는 y에 x를 더한다는 의미다.

tensor([[1.5141, 0.8772],
        [0.8685, 1.2458]])

In [15]:
print("원래 y: ",y)
y.add_(x)
print("y=y+x: ",y)

#y=y+x
#y.add_는 y에 x를 더한 값을 y에 대체한다.(inplace 방식)

원래 y:  tensor([[0.8839, 0.8771],
        [0.0025, 0.2814]])
y=y+x:  tensor([[1.5141, 0.8772],
        [0.8685, 1.2458]])


### 텐서의 크기 변환하기

In [16]:
x = torch.rand(8,8) #8x8 랜덤 행렬
print(x.size())

torch.Size([8, 8])


In [17]:
a = x.view(64) #크기를 바꿔주는 view 8*8 -> 64
print(a.size())

torch.Size([64])


In [19]:
b=x.view(-1,4,4) #-1은 원래 크기가 되게 하는 값 8*8 -> -1*4*4 즉, 4*4*4
print(b.size())
#따라서 -1은 원래 크기가 되게 하는 값이 자동으로 지정되기 때문에 한번만 사용할 수 있다.
#예를 들어 x.vies(-1,-1,4) 와 같은 선언은 오류가 난다

torch.Size([4, 4, 4])


### 텐서에서 넘파이로 만들기

In [20]:
x = torch.rand(8,8)
y = x.numpy()
print(y)

[[0.8232479  0.92056006 0.7245373  0.08221871 0.998958   0.00802636
  0.06239682 0.5851239 ]
 [0.5231064  0.13294476 0.11706138 0.6850346  0.7328036  0.1667605
  0.29447603 0.62116987]
 [0.87663084 0.5357705  0.27606565 0.70053667 0.85959876 0.73105454
  0.6515315  0.18801945]
 [0.09091496 0.866185   0.19139743 0.9533003  0.19717932 0.8616204
  0.7929016  0.22976267]
 [0.9777911  0.18229026 0.0580892  0.00933158 0.9553751  0.47195143
  0.14681125 0.4456675 ]
 [0.72767687 0.85544115 0.7193568  0.18548429 0.7477083  0.36657286
  0.43108457 0.34424227]
 [0.9269169  0.87806517 0.2196061  0.69037867 0.6207518  0.3062632
  0.81314087 0.99899983]
 [0.5516289  0.562908   0.35540485 0.82363087 0.4568448  0.16054833
  0.1053021  0.04783756]]


In [21]:
type(y)

numpy.ndarray

### 단일 텐서에서 값으로 뽑아내기

In [22]:
loss = torch.ones(1)

In [23]:
print(loss)
print(loss.item())
#.item()은 손실 함수값과 같이 숫자가 하나인 텐서를 텐서가 아닌 값으로 만들어 준다.

tensor([1.])
1.0
